package com.s.ecoflux.plant.tree.morphology;

/**
 * Record representing one node in a parametric tree skeleton.
 *
 * <p>Structure: Position ({@link net.minecraft.core.BlockPos}), type
 * ({@link NodeType}), radius (thickness at this node), parentIndex (index into
 * the owning {@link TreeSkeleton#nodes()} list, -1 for root), and depth
 * (distance in hops from the root node).
 *
 * <p>Role in Ecoflux: The atomic unit of the morphology skeleton system. Nodes form
 * a hierarchical tree graph stored in {@link TreeSkeleton}. Generated by
 * {@link SkeletonGenerator}, consumed by {@link CanopyEnvelope} for density
 * calculation and {@link LeafFiller} for proximity-based leaf placement.
 */

import net.minecraft.core.BlockPos;

public record SkeletonNode(
        BlockPos pos,
        NodeType type,
        float radius,
        int parentIndex,
        int depth
) {}
