package com.s.ecoflux.plant.tree.morphology;

/**
 * Mutable data structure holding the complete skeleton of a growing tree.
 *
 * <p>Structure: A flat list of {@link SkeletonNode}s with index-based parent
 * references forming a tree graph. Also stores: root index, trunk path indices,
 * primary branch start indices, sapling position, and trunk level count (for 2x2).
 * All accessors return unmodifiable views of internal lists.
 *
 * <p>Role in Ecoflux: Intermediate representation between skeleton generation and
 * block placement. Generated by {@link SkeletonGenerator#generate}, stored
 * transiently in {@link com.s.ecoflux.plant.tree.TreeGrowthSession}, consumed by
 * {@link CanopyEnvelope} and {@link LeafFiller} to drive progressive tree growth.
 */

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import net.minecraft.core.BlockPos;

public final class TreeSkeleton {
    private final List<SkeletonNode> nodes = new ArrayList<>();
    private int rootIndex = -1;
    private final List<Integer> trunkPath = new ArrayList<>();
    private final List<Integer> primaryBranches = new ArrayList<>();
    private BlockPos saplingPos;
    private int trunkLevels;

    public TreeSkeleton() {}

    public int addNode(SkeletonNode node) {
        int index = nodes.size();
        nodes.add(node);
        return index;
    }

    public SkeletonNode getNode(int index) {
        return nodes.get(index);
    }

    public List<SkeletonNode> nodes() {
        return Collections.unmodifiableList(nodes);
    }

    public int rootIndex() {
        return rootIndex;
    }

    public void setRootIndex(int index) {
        this.rootIndex = index;
    }

    public List<Integer> trunkPath() {
        return Collections.unmodifiableList(trunkPath);
    }

    public void addTrunkNode(int index) {
        trunkPath.add(index);
    }

    public List<Integer> primaryBranches() {
        return Collections.unmodifiableList(primaryBranches);
    }

    public void addPrimaryBranch(int index) {
        primaryBranches.add(index);
    }

    public BlockPos saplingPos() {
        return saplingPos;
    }

    public void setSaplingPos(BlockPos pos) {
        this.saplingPos = pos;
    }

    public int nodeCount() {
        return nodes.size();
    }

    public int trunkHeight() {
        return trunkLevels > 0 ? trunkLevels : trunkPath.size();
    }

    public void setTrunkLevels(int levels) {
        this.trunkLevels = levels;
    }
}
