package com.cp.ecoflux.attachment;

/**
 * Pre-generated plant spawn entry queued for placement into the world.
 *
 * <p>Structure: immutable record carrying a plant definition id, point value,
 * spawn weight, and maximum age in ticks. Supports NBT round-tripping via
 * {@code toTag()}/{@code fromTag()}.
 *
 * <p>Role in Ecoflux: entries are generated by {@code PlantSpawner.buildWeightedQueue()}
 * from succession path configuration, stored in {@code SuccessionChunkData}'s
 * plant queue, and consumed one-by-one as plants are spawned into the chunk.
 */

import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceLocation;

public record PlantQueueEntry(ResourceLocation plantId, int pointValue, int weight, long maxAgeTicks) {
    private static final String PLANT_ID = "plant_id";
    private static final String POINT_VALUE = "point_value";
    private static final String WEIGHT = "weight";
    private static final String MAX_AGE_TICKS = "max_age_ticks";

    public CompoundTag toTag() {
        CompoundTag tag = new CompoundTag();
        tag.putString(PLANT_ID, plantId.toString());
        tag.putInt(POINT_VALUE, pointValue);
        tag.putInt(WEIGHT, weight);
        tag.putLong(MAX_AGE_TICKS, maxAgeTicks);
        return tag;
    }

    public static PlantQueueEntry fromTag(CompoundTag tag) {
        return new PlantQueueEntry(
                ResourceLocation.parse(tag.getString(PLANT_ID)),
                tag.getInt(POINT_VALUE),
                tag.getInt(WEIGHT),
                tag.getLong(MAX_AGE_TICKS));
    }
}
